version: v1alpha
name: "retail_acn_inventory"  # change as per name of semantic model
layer: user
type: lens
tags:
  - Tier.Gold
description: Data model for supply chain intelligence 
lens:
  compute: runnable-default
  # secrets:
  #   - name: retail_acn_inventory # Secret name, secret used for access to the semantic model from git repository.
  #     allKeys: true
  source:
    type: minerva    # Query engine type.
    name: minervac   # Cluster name; this cluster should include all RDBMS depots (catalogs) used by the semantic model SQL files.
    catalog: postgresdb # Depot (catalog) name; this depot should include all RDBMS based depots (catalogs) used by the semantic model SQL files.
  repo:  # Repository URL and base directory for the semantic model SQL files.
    url: https://github.com/samarthsikand/tmdc_acn_test
    lensBaseDir: tmdc_acn_test
    syncFlags:     # Branch name to sync from.
      - --ref=main

  api:   # API configuration.
    replicas: 1 # Number of replicas.
    logLevel: info  # Log level.
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
    resources: # Resources for the API.
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
  worker: # optional
    replicas: 1 # optional
    logLevel: debug  # optional
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
    resources: # optional
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
  router: # optional
    logLevel: info  # optional
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
    resources: # optional
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi

  metric: # optional
    logLevel: info  # optional
    replicas: 1 # optional
    resources:   # optional
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi





